<!-- Content Header (Page header) -->
<script src="<?php echo COMMON; ?>js/datatable.js"></script>
<section class="content-header">
    <h1>
        Nuestro voluntariado
        <small>Administracion</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?php echo $this->metodo; ?></a></li>
        <li class="active"><?php echo $this->metodoaccion; ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid" id="vista">
        <div class="row">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Agendar Comite</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="example">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Fecha Solicitud</th>
                                    <th>Acta</th>
                                    <th>Solicita</th>
                                    <th>Fecha Comite</th>
                                    <th>Hora Comite</th>
                                    <th>Aprendices</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php for ($i = 0; $i < count($this->comites); $i++): ?>
                                    <tr>
                                        <td><?php echo $i + 1; ?></td> 
                                        <td><?php echo $this->comites[$i]['comFechaSolicitud']; ?></td>
                                        <td><a href="<?php echo $this->comites[$i]['actRuta']; ?>" target="_blank">Acta No <?php echo $this->comites[$i]['actNumero']; ?></a></td>
                                        <td><?php echo ucwords(strtolower($this->comites[$i]['usuNombre'] . ' ' . $this->comites[$i]['usuApellido'])); ?></td>
                                        <td>
                                            <?php if (!empty($this->comites[$i]['comFechaComite'])) { ?>
                                                <?php echo $this->comites[$i]['comFechaComite']; ?>
                                            <?php } else { ?>
                                                Por definir
                                            <?php } ?>
                                        </td>
                                        <td>
                                            <?php if (!empty($this->comites[$i]['comHoraComite'])) { ?>
                                                <?php echo $this->comites[$i]['comHoraComite']; ?>
                                            <?php } else { ?>
                                                Por definir
                                            <?php } ?>
                                        </td>
                                        <td>
                                            <table>
                                                <?php for ($j = 0; $j < count($this->comites[$i]['aprendices']); $j++) { ?>
                                                    <tr>
                                                        <td><span class="glyphicon glyphicon-play"></span> <?php echo ucwords(strtolower($this->comites[$i]['aprendices'][$j]['aprendizusuNombre'] . ' ' . $this->comites[$i]['aprendices'][$j]['aprendizusuApellido'])) . ' (' . $this->comites[$i]['aprendices'][$j]['fchaNumero'] . ')'; ?></td>
                                                    </tr>
                                                <?php } ?>
                                            </table>
                                        </td>
                                        <td class="text-center">
                                                <button class="btn btn-success" value="<?php echo $this->comites[$i]['comId']; ?>" id="btnAgendar"><span class="glyphicon glyphicon-check"></span></button>
                                        </td>
                                    </tr>
                                <?php endfor; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" tabindex="-1" id="modalAgendarComites" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">Mensaje de confirmacion<button class="close" data-dismiss="modal">&times;</button></div>
                <div class="modal-body">
                    <div id="contenidoModal"></div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function () {
        var host = 'http://localhost/vidar/';
        $(document).on('click', '#btnAgendar', function () {
            var data = {
                'id': $(this).val()
            };
            $('#modalAgendarComites').modal('show');
            cargadivconsulta('contenidoModal', host + 'procesos/setagendarcomite/', data);
        });
    });
</script>





