<script src="<?php echo COMMON; ?>js/datatable.js"></script>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <?php echo SUB_NAME; ?>
        <small>Administracion</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?php echo $this->metodo; ?></a></li>
        <li class="active"><?php echo $this->metodoaccion; ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid" id="vista">
        <div class="row">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Listado usuarios</h3>
                </div>
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table-bordered table table-condensed table-responsive table-hover" id="example">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Tipo</th>
                                    <th>Documento</th>
                                    <th>Nombre</th>
                                    <th>Apellido</th>
                                    <th>Correo</th>
                                    <th>Telefono</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php for ($i = 0; $i < count($this->usuarios); $i++): ?>
                                    <tr>
                                        <td><?php echo $i + 1; ?></td>
                                        <td><?php echo $this->usuarios[$i]['usuTipoDocu']; ?></td>
                                        <td><?php echo $this->usuarios[$i]['usuDocumento']; ?></td>
                                        <td><?php echo ucwords(strtolower($this->usuarios[$i]['usuNombre'])); ?></td>
                                        <td><?php echo ucwords(strtolower($this->usuarios[$i]['usuApellido'])); ?></td>
                                        <td><?php echo $this->usuarios[$i]['usuCorreo']; ?></td>
                                        <td><?php echo $this->usuarios[$i]['usuTelefono']; ?></td>
                                        <td>
                                            <button id="btnAutorizar" value="<?php echo $this->usuarios[$i]['usuId']; ?>" class="btn btn-success"><span class="glyphicon glyphicon-check"></span></button>
                                        </td>
                                    </tr>
                                <?php endfor; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" tabindex="-1" id="modalAutorizar" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">Mensaje de confirmacion<button class="close" data-dismiss="modal">&times;</button></div>
            <div class="modal-body">
                <div id="contenidoModal"></div>
            </div>
        </div>
    </div>
</div>
