<!-- general form elements -->
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Finalizar plan de mejoramiento</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" enctype="multipart/form-data" method="post" action="<?php echo RUTA_URL . 'procesos/setcalificacionplanmejoramiento'; ?>">
        <div class="box-body">
            <input type="hidden" name="txtCodigo" id="txtCodigo" value="<?php echo $this->datos[0]['planId']; ?>">
            <div class="form-group">
                <label for="exampleInputEmail1">Fecha plazo entrega</label>
                <input type="text" disabled placeholder="yyyy/mm/dd" value="<?php echo $this->datos[0]['planPlazoEntrega']; ?>" id="txtFechallamado" class="form-control datepicker" name="txtFecha">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Descripcion actividad</label>
                <textarea disabled class="form-control" name="txtDescripcionActividad"><?php echo $this->datos[0]['planDescripcionActividad']; ?></textarea>
            </div>
            <div id="tablaAprendicesplan">
                <table class="table-bordered table table-condensed table-responsive table-hover" id="example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tipo</th>
                            <th>Documento</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th class="text-center">A</th>
                            <th class="text-center">N</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php for ($i = 0; $i < count($this->datos[0]['aprendices']); $i++): ?>
                            <tr>
                                <td><?php echo $i + 1; ?></td>
                                <td><?php echo $this->datos[0]['aprendices'][$i]['usuTipoDocu']; ?></td>
                                <td><?php echo $this->datos[0]['aprendices'][$i]['usuDocumento']; ?></td>
                                <td><?php echo ucwords(strtolower($this->datos[0]['aprendices'][$i]['usuNombre'])); ?></td>
                                <td><?php echo ucwords(strtolower($this->datos[0]['aprendices'][$i]['usuApellido'])); ?></td>
                                <td class="text-center">
                                    <input type="checkbox" name="txtNota[]" id="checkaprendices" data-id="<?php echo $i; ?>" class="seleccione<?php echo $i; ?>" value="<?php echo $this->datos[0]['aprendices'][$i]['detPlanId'] . '-A'; ?>">
                                </td>
                                <td class="text-center">
                                    <input type="checkbox" name="txtNota[]" id="checkaprendices" data-id="<?php echo $i; ?>" class="seleccione<?php echo $i; ?>" value="<?php echo $this->datos[0]['aprendices'][$i]['detPlanId'] . '-N'; ?>">
                                </td>
                            </tr>
                        <?php endfor; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        </div>
    </form>
</div>
