<label class="form-control" style="width: 180px;">
    Novedades predefinidas
</label>
<table class="table-bordered table table-condensed table-responsive table-hover" id="example2">
    <thead>
        <tr>
            <th>#</th>
            <th>Novedad</th>
            <th>Deber Aprendiz</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php for ($i = 0; $i < count($this->novedades); $i++): ?>
            <tr>
                <td><?php echo $i + 1; ?></td>
                <td><?php echo $this->novedades[$i]['novpNovedad']; ?></td>
                <td><?php echo $this->novedades[$i]['debDescripcion']; ?></td>
                <td class="text-center">
                    <input name="txtNovedad[]" type="checkbox" value="<?php echo $this->novedades[$i]['novpId']; ?>">
                </td>
            </tr>
        <?php endfor; ?>
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $('#example2').dataTable({
            "paging": false,
            "ordering": false,
            "info": false,
            "responsive": true,
            oLanguage: {
                "sSearch": "Buscar:"
            }
        });
    });
</script>

