<!-- general form elements -->
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Formulario Agendar Comite</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" enctype="multipart/form-data" method="post" action="<?php echo RUTA_URL . 'procesos/guardardatoscomite'; ?>">
        <div class="box-body">
            <input type="hidden" name="txtCodigo" value="<?php echo $this->id; ?>">
            <div class="form-group">
                <label for="exampleInputEmail1">Fecha Comite</label>
                <input type="text" placeholder="yyyy/mm/dd" value="<?php echo $this->datos[0]['comFechaComite']; ?>" id="txtFechallamado" class="form-control datepicker" name="txtFecha">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Hora Comite</label>
                <div class="input-group">
                    <input type="text" name="txtHora" value="<?php echo $this->datos[0]['comHoraComite']; ?>" class="form-control timepicker">
                    <div class="input-group-addon">
                        <i class="fa fa-clock-o"></i>
                    </div>
                </div>
            </div>
            <div id="tablaInstructores">
                <table class="table-bordered table table-condensed table-responsive table-hover" id="example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tipo</th>
                            <th>Documento</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php for ($i = 0; $i < count($this->usuarios); $i++): ?>
                            <tr>
                                <td><?php echo $i + 1; ?></td>
                                <td><?php echo $this->usuarios[$i]['usuTipoDocu']; ?></td>
                                <td><?php echo $this->usuarios[$i]['usuDocumento']; ?></td>
                                <td><?php echo ucwords(strtolower($this->usuarios[$i]['usuNombre'])); ?></td>
                                <td><?php echo ucwords(strtolower($this->usuarios[$i]['usuApellido'])); ?></td>
                                <td class="text-center">
                                    <?php if ($this->usuarios[$i]['estado'] == 'A') { ?>
                                        <input type="hidden" name="txtAsistencia[]" value="<?php echo $this->usuarios[$i]['detComId']; ?>">
                                        <input checked name="txtInstructores[]" type="checkbox" value="<?php echo $this->usuarios[$i]['usuId']; ?>">
                                        <button type="button" data-comite="<?php echo $this->id; ?>" value="<?php echo $this->usuarios[$i]['detComId']; ?>" class="close" id="btnQuitar">&times;</button>
                                    <?php } else { ?>
                                        <input type="hidden" name="txtAsistencia[]" value="">
                                        <input name="txtInstructores[]" type="checkbox" value="<?php echo $this->usuarios[$i]['usuId']; ?>">
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php endfor; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        </div>
    </form>
</div>
<script>
    $(document).ready(function () {
        $('.datepicker').datepicker({
            autoclose: true,
            format: 'yyyy/mm/dd'
        });
        $('.timepicker').timepicker({
            showInputs: false
        });
    });
</script>