<!-- general form elements -->
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title"><?php echo $this->accion; ?></h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" enctype="multipart/form-data" method="post" action="<?php echo RUTA_URL . 'procesos/setplanmejoramiento'; ?>">
        <div class="box-body">
            <input type="hidden" name="txtCodigo" id="txtCodigo" value="<?php echo $this->datos[0]['planId']; ?>">
            <div class="form-group">
                <label for="exampleInputEmail1">Fecha plazo entrega</label>
                <input type="text" placeholder="yyyy/mm/dd" value="<?php echo $this->datos[0]['planPlazoEntrega']; ?>" id="txtFechallamado" class="form-control datepicker" name="txtFecha">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Descripcion actividad</label>
                <textarea class="form-control" name="txtDescripcionActividad"><?php echo $this->datos[0]['planDescripcionActividad']; ?></textarea>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Institucion</label>
                <select id="selInstitucion2" name="txtInstitucion" class="form-control">
                    <option disabled selected>--Seleccione--</option>
                    <?php for ($i = 0; $i < count($this->instituciones); $i++) { ?>
                        <?php if ($this->instituciones[$i]['instId'] == $this->datos[0]['instId']) { ?>
                            <option value="<?php echo $this->instituciones[$i]['instId']; ?>" selected><?php echo $this->instituciones[$i]['instNombre']; ?></option>
                        <?php } else { ?>
                            <option value="<?php echo $this->instituciones[$i]['instId']; ?>"><?php echo $this->instituciones[$i]['instNombre']; ?></option>
                        <?php } ?>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Programa</label>
                <div id="cargarProgramas2">
                    <select id="selPrograma2" class="form-control" name="txtPrograma">
                        <option disabled selected>--Seleccione--</option>
                        <?php for ($i = 0; $i < count($this->programas); $i++) { ?>
                            <?php if ($this->programas[$i]['proId'] == $this->datos[0]['proId']) { ?>
                                <option selected value="<?php echo $this->programas[$i]['proId']; ?>"><?php echo $this->programas[$i]['proNombre']; ?></option>
                            <?php } else { ?>
                                <option value="<?php echo $this->programas[$i]['proId']; ?>"><?php echo $this->programas[$i]['proNombre']; ?></option>
                            <?php } ?>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Ficha</label>
                <div id="cargafichas2">
                    <select name="txtInstitucion" class="form-control">
                        <option disabled selected>--Seleccione--</option>
                        <?php for ($i = 0; $i < count($this->fichas); $i++) { ?>
                            <?php if ($this->fichas[$i]['fchaId'] == $this->datos[0]['fchaId']) { ?>
                                <option value="<?php echo $this->fichas[$i]['fchaId']; ?>" selected><?php echo $this->fichas[$i]['fchaNumero']; ?></option>
                            <?php } else { ?>
                                <option value="<?php echo $this->fichas[$i]['fchaId']; ?>"><?php echo $this->fichas[$i]['fchaNumero']; ?></option>
                            <?php } ?>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div id="tablaAprendicesplan">
                <table class="table-bordered table table-condensed table-responsive table-hover" id="example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tipo</th>
                            <th>Documento</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php for ($i = 0; $i < count($this->datos[0]['aprendices']); $i++): ?>
                            <tr>
                                <td><?php echo $i + 1; ?></td>
                                <td><?php echo $this->datos[0]['aprendices'][$i]['usuTipoDocu']; ?></td>
                                <td><?php echo $this->datos[0]['aprendices'][$i]['usuDocumento']; ?></td>
                                <td><?php echo ucwords(strtolower($this->datos[0]['aprendices'][$i]['usuNombre'])); ?></td>
                                <td><?php echo ucwords(strtolower($this->datos[0]['aprendices'][$i]['usuApellido'])); ?></td>
                                <td class="text-center">
                                    <?php if (!empty($this->datos[0]['aprendices'][$i]['detPlanId'])) { ?>
                                        <input type="hidden" name="txtCodigoAprendiz[]" value="<?php echo $this->datos[0]['aprendices'][$i]['detPlanId']; ?>">
                                        <input checked name="txtAprendiz[]" type="checkbox" value="<?php echo $this->datos[0]['aprendices'][$i]['usuId']; ?>">
                                        <button class="close" id="btnEliminarPlanMejoramiento" value="<?php echo $this->datos[0]['aprendices'][$i]['detPlanId']; ?>">&times;</button>
                                    <?php } else { ?>
                                        <input type="hidden" name="txtCodigoAprendiz[]">
                                        <input name="txtAprendiz[]" type="checkbox" value="<?php echo $this->datos[0]['aprendices'][$i]['usuId']; ?>">
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php endfor; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        </div>
    </form>
</div>
<script>
    $(document).ready(function () {
        $('.datepicker').datepicker({
            autoclose: true,
            format: 'yyyy/mm/dd'
        });
        $('.timepicker').timepicker({
            showInputs: false
        });
    });
</script>
