<script src="<?php echo COMMON; ?>js/datatable.js"></script><!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <?php echo SUB_NAME; ?>
        <small>Administracion</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?php echo $this->metodo; ?></a></li>
        <li class="active"><?php echo $this->metodoaccion; ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid" id="vista">
        <div class="row">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Plan de mejoramiento</h3>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-3">
                            <label>
                                Institucion
                            </label>
                            <select id="selInstitucion" class="form-control">
                                <option disabled selected>--Seleccione--</option>
                                <?php for ($i = 0; $i < count($this->instituciones); $i++) { ?>
                                    <option value="<?php echo $this->instituciones[$i]['instId']; ?>"><?php echo $this->instituciones[$i]['instNombre']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <label>
                                Programa
                            </label>
                            <div id="cargarProgramas">
                                <select id="selPrograma" class="form-control">
                                    <option disabled selected>--Seleccione--</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label>
                                Ficha
                            </label>
                            <div id="cargafichas">
                                <select class="form-control">
                                    <option disabled selected>--Seleccione--</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <button id="btnbuscarPlanesMejoramiento" style="margin-top: 25px;" class="btn btn-primary">Buscar</button>
                        </div>
                    </div>
                    <button class="btn btn-primary" id="btnAgregarPlan" style="margin-top: 20px;">Agregar</button>
                    <div style="margin-top: 30px;" id="cargarTablaPlanesMejoramiento" class="table-responsive">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="example">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Fecha Solicitud</th>
                                        <th style="width: 80px;">Fecha Plazo</th>
                                        <th>Actividad</th>
                                        <th>Solicitante</th>
                                        <th>Aprendices</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php for ($i = 0; $i < count($this->planes); $i++) { ?>
                                        <tr>
                                            <td><?php echo $i + 1; ?></td>
                                            <td><?php echo $this->planes[$i]['planFecha']; ?></td>
                                            <td><?php echo $this->planes[$i]['planPlazoEntrega']; ?></td>
                                            <td><?php echo $this->planes[$i]['planDescripcionActividad']; ?></td>
                                            <td><?php echo ucwords(strtolower($this->planes[$i]['usuNombre'] . ' ' . $this->planes[$i]['usuApellido'])); ?></td>
                                            <td>
                                                <table>
                                                    <?php for ($j = 0; $j < count($this->planes[$i]['aprendices']); $j++) { ?>
                                                        <tr>
                                                            <td><span class="glyphicon glyphicon-play"></span> <?php echo ucwords(strtolower($this->planes[$i]['aprendices'][$j]['usuNombre'] . ' ' . $this->planes[$i]['aprendices'][$j]['usuApellido'])); ?></td>
                                                        </tr>
                                                    <?php } ?>
                                                </table>
                                            </td>
                                            <td style="width: 150px;" class="text-center">
                                                <?php if ($this->planes[$i]['planEstado'] == 'Pendiente') { ?>
                                                    <button id="btnCalificarPlan" value="<?php echo $this->planes[$i]['planId']; ?>" class="btn btn-success">
                                                        <span class="glyphicon glyphicon-check"></span>
                                                    </button>
                                                    <button data-toggle="modal" data-target="#modalEliminarPlanes" data-id="<?php echo $this->planes[$i]['planId']; ?>" class="btn btn-danger">
                                                        <span class="glyphicon glyphicon-remove"></span>
                                                    </button>
                                                    <button id="btnEditarPlan" value="<?php echo $this->planes[$i]['planId']; ?>" class="btn btn-warning">
                                                        <span class="glyphicon glyphicon-edit"></span>
                                                    </button>
                                                <?php } else { ?>
                                                    <button class="btn btn-primary" value="<?php echo $this->planes[$i]['planId']; ?>" id="btnVerDatosPlan">
                                                        <span class="glyphicon glyphicon-list-alt"></span>
                                                    </button>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" tabindex="-1" id="modalplanesMejoramiento" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">Mensaje de confirmacion<button class="close" data-dismiss="modal">&times;</button></div>
            <div class="modal-body">
                <div id="contenidoModal"></div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" tabindex="-1" id="modalEliminarPlanes" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">Mensaje de confirmacion<button class="close" data-dismiss="modal">&times;</button></div>
            <div class="modal-body">
                <h3>¿Esta seguro que desea eliminar este plan de mejoramiento?</h3>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-warning" id="enviar">Si</a>
                <a href="#" class="btn btn-danger" data-dismiss="modal">No</a>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var host = 'http://localhost/vidar/';
        //var host = 'https://ganadinero.000webhostapp.com/vidar/';
        $('#modalEliminarPlanes').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var recipent = button.data('id')
            var modal = $(this);
            modal.find('h3').text('¿Esta seguro que desea eliminar este plan de mejoramiento?');
            modal.find('#enviar').attr('href', host + 'procesos/bajaplanesmejoramiento/' + recipent);
        });
    });
</script>
