<table class="table-bordered table table-condensed table-responsive table-hover" id="example">
    <thead>
        <tr>
            <th>#</th>
            <th>Tipo</th>
            <th>Documento</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php for ($i = 0; $i < count($this->datos); $i++): ?>
            <tr>
                <td><?php echo $i + 1; ?></td>
                <td><?php echo $this->datos[$i]['usuTipoDocu']; ?></td>
                <td><?php echo $this->datos[$i]['usuDocumento']; ?></td>
                <td><?php echo ucwords(strtolower($this->datos[$i]['usuNombre'])); ?></td>
                <td><?php echo ucwords(strtolower($this->datos[$i]['usuApellido'])); ?></td>
                <td class="text-center">
                    <?php if (!empty($this->datos[$i]['detPlanId'])) { ?>
                        <input type="hidden" name="txtCodigoAprendiz[]" value="<?php echo $this->datos[$i]['detPlanId']; ?>">
                        <input checked name="txtAprendiz[]" type="checkbox" value="<?php echo $this->datos[$i]['usuId']; ?>">
                        <button class="close" id="btnEliminarPlanMejoramiento" value="<?php echo $this->datos[$i]['detPlanId']; ?>">&times;</button>
                    <?php } else { ?>
                        <input type="hidden" name="txtCodigoAprendiz[]">
                        <input name="txtAprendiz[]" type="checkbox" value="<?php echo $this->datos[$i]['usuId']; ?>">
                    <?php } ?>
                </td>
            </tr>
        <?php endfor; ?>
    </tbody>
</table>
