<?php if ($this->response == 1) { ?>
    <script src='<?php echo COMMON; ?>js/validar.js'></script>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="box box-primary">
                        <form method="post" id="form1" action="<?php echo RUTA_URL . 'inicio/setpassword'; ?>">
                            <div class="box-header with-border">
                                <h3 class="box-title">Formulario cambiar contraseña</h3>
                            </div>
                            <div class="box-body">
                                <div class="form-group">
                                    <label>Digite contraseña nueva</label>
                                    <input type="password" name="password" class="form-control" id="txtPasswordDatos">
                                </div>
                                <div class="form-group">
                                    <label>Comfirme contraseña</label>
                                    <input type="password" name="confirmPassword" class="form-control" id="txtPasswordDatos">
                                </div>
                                <div class="form-group">
                                    <input type="submit" class="btn btn-primary" value="Guardar">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row">
                <div id="MostrarResultadoCuenta"></div>
            </div>
        </div>
    </section>
<?php } else { ?>
    <div class="alert alert-danger" role="alert">Error, verifique su contraseña</div>
<?php } ?>



