<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Vidar
        <small>Administracion</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?php echo $this->metodo; ?></a></li>
        <li class="active"><?php echo $this->metodoaccion; ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Login Usuario</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="<?php echo RUTA_URL . 'inicio/setlogin'; ?>">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Correo</label>
                            <input name="txtCorreo" type="text" value="<?php echo $_COOKIE['user']; ?>" class="form-control" id="exampleInputEmail1" placeholder="Correo">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Contraseña</label>
                            <input name="txtPassword" type="password" value="<?php echo $_COOKIE['pass']; ?>" class="form-control" id="exampleInputPassword1" placeholder="Password">
                        </div>
                        <div class="checkbox">
                            <label>
                                <?php if (isset($_COOKIE['user']) && $_COOKIE['pass']) { ?>
                                    <input checked name="txtRecordarme" value="A" type="checkbox"> Recordarme
                                <?php } else { ?>
                                    <input name="txtRecordarme" value="A" type="checkbox"> Recordarme
                                <?php } ?>
                            </label>
                        </div>
                        <div class="form-group">

                            ¡No tienes una cuenta! <a href="<?php echo RUTA_URL . 'inicio/registrarse'; ?>"> Registrate</a>
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</section>