<!-- Content Header (Page header) -->
<script src='<?php echo COMMON; ?>js/validar.js'></script>
<section class="content-header">
    <h1>
        Vidar
        <small>Administracion</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?php echo $this->metodo; ?></a></li>
        <li class="active"><?php echo $this->metodoaccion; ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">    
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Datos usuario</h3>
                </div>
                <div class="box-body">
                    <form id="form1" method="post" action="<?php echo RUTA_URL . 'inicio/guardardatos'; ?>">
                        <div class="form-group">
                            <label>
                                Tipo Documento
                            </label>
                            <div>
                                <select class="form-control" name="txtTipo">
                                    <option disabled selected>--Seleccione--</option>
                                    <option value="CC">Cédula de Ciudadanía</option>
                                    <option value="TI">Tarjeta de Identidad</option>
                                    <option value="CE">Cédula de Extranjería</option>
                                    <option value="PS">Pasaporte</option>
                                    <option value="DNI">Documento Nacional de Identificación</option>
                                    <option value="NIT">Número de Identificación Tributaria</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>
                                Documento
                            </label>
                            <div>
                                <input name="txtDocumento" type="number" class="form-control" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>
                                Nombres
                            </label>
                            <div>
                                <input type="text" name="txtNombre" class="form-control" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>
                                Apellidos
                            </label>
                            <div>
                                <input type="text" name="txtApellido" class="form-control" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>
                                Correo
                            </label>
                            <div>
                                <input type="text" class="form-control" name="txtCorreo">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>
                                Telefono
                            </label>
                            <div>
                                <input type="number" class="form-control" name="txtTelefono">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>
                                Contraseña
                            </label>
                            <div>
                                <input type="password" class="form-control" name="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>
                                Confirme Contraseña
                            </label>
                            <div>
                                <input type="password" class="form-control" name="confirmPassword">
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" id="enviarHuellas" class="btn btn-success" value="Guardar">&nbsp;<a href="<?php echo RUTA_URL . 'inicio/index'; ?>" class="btn btn-danger">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</section>