<!-- general form elements -->
<?php for ($i = 0; $i < count($this->novedades); $i++) { ?>
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Novedad No <?php echo $i + 1; ?></h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <div class="box-body">
            <div class="form-group">
                <label>Tipo novedad</label>
                <input type="text" class="form-control" value="<?php echo $this->novedades[$i]['rnovTipo']; ?>" disabled>
            </div>
            <div class="form-group">
                <label>Descripcion novedad</label>
                <textarea class="form-control" disabled><?php echo $this->novedades[$i]['rnovDescripcion']; ?></textarea>
            </div>
            <div class="form-group">
                <label>Fecha novedad</label>
                <input type="text" disabled class="form-control" value="<?php echo $this->novedades[$i]['rnovFecha']; ?>">
            </div>
            <div class="form-group">
                <label>Hora novedad</label>
                <input type="text" disabled class="form-control" value="<?php echo $this->novedades[$i]['rnovHora']; ?>">
            </div>
            <div class="form-group">
                <label>Novedad</label>
                <textarea class="form-control" disabled><?php echo $this->novedades[$i]['novpNovedad']; ?></textarea>
            </div>
            <div class="form-group">
                <label>Reglamento aprendiz</label>
                <textarea class="form-control" disabled><?php echo $this->novedades[$i]['debDescripcion']; ?></textarea>
            </div>
        </div>
    </div>
<?php } ?>

