<script src="<?php echo COMMON; ?>js/datatable.js"></script><!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <?php echo SUB_NAME; ?>
        <small>Administracion</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?php echo $this->metodo; ?></a></li>
        <li class="active"><?php echo $this->metodoaccion; ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid" id="vista">
        <div class="row">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Reporte comite de evaluacion y seguimiento</h3>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-3">
                            <label>
                                Institucion
                            </label>
                            <select id="selInstitucion" class="form-control">
                                <option disabled selected>--Seleccione--</option>
                                <?php for ($i = 0; $i < count($this->instituciones); $i++) { ?>
                                    <option value="<?php echo $this->instituciones[$i]['instId']; ?>"><?php echo $this->instituciones[$i]['instNombre']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <label>
                                Programa
                            </label>
                            <div id="cargarProgramas">
                                <select id="selPrograma" class="form-control">
                                    <option disabled selected>--Seleccione--</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label>
                                Ficha
                            </label>
                            <div id="cargafichas">
                                <select class="form-control">
                                    <option disabled selected>--Seleccione--</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <button id="btnbuscarComiteFiltro" style="margin-top: 25px;" class="btn btn-primary">Buscar</button>
                        </div>
                    </div>
                    <div style="margin-top: 30px;" id="cargarTablaFiltroComite" class="table-responsive">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="example">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Fecha Solicitud</th>
                                        <th>Acta</th>
                                        <th>Solicita</th>
                                        <th>Fecha Comite</th>
                                        <th>Hora Comite</th>
                                        <th>Aprendices</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php for ($i = 0; $i < count($this->comites); $i++): ?>
                                        <tr>
                                            <td><?php echo $i + 1; ?></td> 
                                            <td><?php echo $this->comites[$i]['comFechaSolicitud']; ?></td>
                                            <td><a href="<?php echo $this->comites[$i]['actRuta']; ?>" target="_blank">Acta No <?php echo $this->comites[$i]['actNumero']; ?></a></td>
                                            <td><?php echo ucwords(strtolower($this->comites[$i]['usuNombre'] . ' ' . $this->comites[$i]['usuApellido'])); ?></td>
                                            <td>
                                                <?php if (!empty($this->comites[$i]['comFechaComite'])) { ?>
                                                    <?php echo $this->comites[$i]['comFechaComite']; ?>
                                                <?php } else { ?>
                                                    Por definir
                                                <?php } ?>
                                            </td>
                                            <td>
                                                <?php if (!empty($this->comites[$i]['comHoraComite'])) { ?>
                                                    <?php echo $this->comites[$i]['comHoraComite']; ?>
                                                <?php } else { ?>
                                                    Por definir
                                                <?php } ?>
                                            </td>
                                            <td>
                                                <table>
                                                    <?php for ($j = 0; $j < count($this->comites[$i]['aprendices']); $j++) { ?>
                                                        <tr>
                                                            <td><span class="glyphicon glyphicon-play"></span> <?php echo ucwords(strtolower($this->comites[$i]['aprendices'][$j]['aprendizusuNombre'] . ' ' . $this->comites[$i]['aprendices'][$j]['aprendizusuApellido'])) . ' (' . $this->comites[$i]['aprendices'][$j]['fchaNumero'] . ')'; ?></td>
                                                        </tr>
                                                    <?php } ?>
                                                </table>
                                            </td>
                                            <td style="width: 140px;" class="text-center">
                                                <?php if ($this->comites[$i]['boton'] == 'A') { ?>
                                                    <button value="<?php echo $this->comites[$i]['comId']; ?>" class="btn btn-primary" id="btnPlanMejoramiento"><span class="glyphicon glyphicon-list-alt"></span></button>
                                                <?php } ?>
                                                <button value="<?php echo $this->comites[$i]['comId']; ?>" class="btn btn-primary" id="btnInformacionComite"><span class="glyphicon glyphicon-user"></span></button>
                                            </td>
                                        </tr>
                                    <?php endfor; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" tabindex="-1" id="modalComites" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">Mensaje de confirmacion<button class="close" data-dismiss="modal">&times;</button></div>
            <div class="modal-body">
                <div id="contenidoModal"></div>
            </div>
        </div>
    </div>
</div>
