<script src="<?php echo COMMON; ?>js/datatable.js"></script>
<table class="table-bordered table table-condensed table-responsive table-hover" id="example">
    <thead>
        <tr>
            <th>#</th>
            <th>Tipo</th>
            <th>Documento</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Correo</th>
            <th>Telefono</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php for ($i = 0; $i < count($this->usuarios); $i++): ?>
            <tr>
                <td><?php echo $i + 1; ?></td>
                <td><?php echo $this->usuarios[$i]['usuTipoDocu']; ?></td>
                <td><?php echo $this->usuarios[$i]['usuDocumento']; ?></td>
                <td><?php echo ucwords(strtolower($this->usuarios[$i]['usuNombre'])); ?></td>
                <td><?php echo ucwords(strtolower($this->usuarios[$i]['usuApellido'])); ?></td>
                <td><?php echo $this->usuarios[$i]['usuCorreo']; ?></td>
                <td><?php echo $this->usuarios[$i]['usuTelefono']; ?></td>
                <td class="text-center">
                    <button id="btnVerNovedades" value="<?php echo $this->usuarios[$i]['usuId']; ?>" class="btn btn-primary" type="button">
                        Novedades <span class="badge"><?php echo $this->usuarios[$i]['novedades']; ?></span>
                    </button>
                </td>
            </tr>
        <?php endfor; ?>
    </tbody>
</table>

