<!-- general form elements -->
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Formulario plan de mejoramiento</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" enctype="multipart/form-data" method="post" action="<?php echo RUTA_URL . 'reportes/guardardatosplan'; ?>">
        <div class="box-body">
            <input type="hidden" name="txtCodigoFicha" value="<?php echo $this->ficha; ?>">
            <div class="form-group">
                <label for="exampleInputEmail1">Fecha plazo entrega</label>
                <input type="text" placeholder="yyyy/mm/dd" value="" id="txtFechallamado" class="form-control datepicker" name="txtFecha">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Descripcion actividad</label>
                <textarea class="form-control" name="txtDescripcionActividad"></textarea>
            </div>
            <div id="tablaInstructores">
                <table class="table-bordered table table-condensed table-responsive table-hover" id="example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tipo</th>
                            <th>Documento</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php for ($i = 0; $i < count($this->usuarios); $i++): ?>
                            <tr id="<?php echo 'fila' . $i; ?>">
                                <td><?php echo $i + 1; ?></td>
                                <td><?php echo $this->usuarios[$i]['usuTipoDocu']; ?></td>
                                <td><?php echo $this->usuarios[$i]['usuDocumento']; ?></td>
                                <td><?php echo ucwords(strtolower($this->usuarios[$i]['usuNombre'])); ?></td>
                                <td><?php echo ucwords(strtolower($this->usuarios[$i]['usuApellido'])); ?></td>
                                <td class="text-center">
                                    <input checked name="txtAprendiz[]" type="checkbox" value="<?php echo $this->usuarios[$i]['usuId']; ?>">
                                </td>
                            </tr>
                        <?php endfor; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        </div>
    </form>
</div>
<script>
    $(document).ready(function () {
        $('.datepicker').datepicker({
            autoclose: true,
            format: 'yyyy/mm/dd'
        });
        $('.timepicker').timepicker({
            showInputs: false
        });
    });
</script>