<div class="col-md-3"></div>
<div class="col-md-6">
    <!-- general form elements -->
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $this->accion; ?></h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" enctype="multipart/form-data" method="post" action="<?php echo RUTA_URL . 'parametros/setreglamento'; ?>">
            <div class="box-body">
                <input type="hidden" name="txtCodigo" value="<?php echo $this->datos[0]['debId']; ?>">
                <div class="form-group">
                    <label for="exampleInputEmail1">Descripcion Deber</label>
                    <textarea class="form-control" name="txtDescripcion"><?php echo $this->datos[0]['debDescripcion']; ?></textarea>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Codigo Deber</label>
                    <input name="txtCodigoReglamento" type="text" value="<?php echo $this->datos[0]['debCodigoReglamento']; ?>" class="form-control" id="exampleInputEmail1" placeholder="Numero Acta">
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a href="<?php echo RUTA_URL . 'parametros/reglamentoaprendiz'; ?>" class="btn btn-danger">volver</a>
            </div>
        </form>
    </div>
</div>
<div class="col-md-3"></div>


