<div class="col-md-3"></div>
<div class="col-md-6">
    <!-- general form elements -->
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $this->accion; ?></h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="post" action="<?php echo RUTA_URL . 'parametros/setfichas'; ?>">
            <div class="box-body">
                <input type="hidden" name="txtCodigo" value="<?php echo $this->datos[0]['fchaId']; ?>">
                <div class="form-group">
                    <label for="exampleInputEmail1">Ficha</label>
                    <input name="txtNumero" type="text" value="<?php echo $this->datos[0]['fchaNumero']; ?>" class="form-control" id="exampleInputEmail1" placeholder="Numero">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Institucion</label>
                    <select id="selInstitucion" name="txtInstitucion" class="form-control">
                        <option disabled selected>--Seleccione--</option>
                        <?php for ($i = 0; $i < count($this->instituciones); $i++) { ?>
                            <?php if ($this->instituciones[$i]['instId'] == $this->datos[0]['fchaIdInstitucion']) { ?>
                                <option value="<?php echo $this->instituciones[$i]['instId']; ?>" selected><?php echo $this->instituciones[$i]['instNombre']; ?></option>
                            <?php } else { ?>
                                <option value="<?php echo $this->instituciones[$i]['instId']; ?>"><?php echo $this->instituciones[$i]['instNombre']; ?></option>
                            <?php } ?>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Programa</label>
                    <div id="cargarProgramas">
                        <select name="txtPrograma" id="selPrograma" class="form-control">
                            <option disabled selected>--Seleccione--</option>
                            <?php for ($i = 0; $i < count($this->programas); $i++) { ?>
                                <?php if ($this->programas[$i]['proId'] == $this->datos[0]['fchaIdPrograma']) { ?>
                                    <option value="<?php echo $this->programas[$i]['proId']; ?>" selected><?php echo $this->programas[$i]['proNombre']; ?></option>
                                <?php } else { ?>
                                    <option value="<?php echo $this->programas[$i]['proId']; ?>"><?php echo $this->programas[$i]['proNombre']; ?></option>
                                <?php } ?>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a href="<?php echo RUTA_URL . 'parametros/fichas'; ?>" class="btn btn-danger">volver</a>
            </div>
        </form>
    </div>
</div>
<div class="col-md-3"></div>


