<div class="col-md-3"></div>
<div class="col-md-6">
    <!-- general form elements -->
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $this->accion; ?></h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="post" action="<?php echo RUTA_URL . 'parametros/setprogramas'; ?>">
            <div class="box-body">
                <input type="hidden" name="txtCodigo" value="<?php echo $this->datos[0]['proId']; ?>">
                <div class="form-group">
                    <label for="exampleInputEmail1">Nombre</label>
                    <input name="txtNombre" type="text" value="<?php echo $this->datos[0]['proNombre']; ?>" class="form-control" id="exampleInputEmail1" placeholder="Programa">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">
                        Institucion
                    </label>
                    <select name="txtInstitucion" class="form-control">
                        <option disabled selected>--Seleccione--</option>
                        <?php for ($i = 0; $i < count($this->instituciones); $i++) { ?>
                            <?php if ($this->datos[0]['proInstitucion'] == $this->instituciones[$i]['instId']) { ?>
                                <option selected value="<?php echo $this->instituciones[$i]['instId']; ?>"><?php echo $this->instituciones[$i]['instNombre']; ?></option>
                            <?php } else { ?>
                                <option value="<?php echo $this->instituciones[$i]['instId']; ?>"><?php echo $this->instituciones[$i]['instNombre']; ?></option>
                            <?php } ?>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a href="<?php echo RUTA_URL . 'parametros/programas'; ?>" class="btn btn-danger">volver</a>
            </div>
        </form>
    </div>
</div>
<div class="col-md-3"></div>

