<div class="col-md-2"></div>
<div class="col-md-8">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $this->accion; ?></h3>
        </div>
        <div class="box-body">
            <form id="form1" method="post" action="<?php echo RUTA_URL . 'parametros/setaprendices'; ?>">
                <input type="hidden" name="txtCodigo" value="<?php echo $this->datos[0]['usuId']; ?>">
                <div class="form-group">
                    <label>
                        Tipo Documento
                    </label>
                    <select class="form-control" name="txtTipo">
                        <option disabled selected>--Seleccione--</option>
                        <?php if ($this->datos[0]['usuTipoDocu'] == 'CC') { ?>
                            <option selected value="CC">Cédula de Ciudadanía</option>
                        <?php } else { ?>
                            <option value="CC">Cédula de Ciudadanía</option>
                        <?php } ?>
                        <?php if ($this->datos[0]['usuTipoDocu'] == 'TI') { ?>
                            <option selected value="TI">Tarjeta de Identidad</option>
                        <?php } else { ?>
                            <option value="TI">Tarjeta de Identidad</option>
                        <?php } ?>
                        <?php if ($this->datos[0]['usuTipoDocu'] == 'CE') { ?>
                            <option selected value="CE">Cédula de Extranjería</option>
                        <?php } else { ?>
                            <option value="CE">Cédula de Extranjería</option>
                        <?php } ?>
                        <?php if ($this->datos[0]['usuTipoDocu'] == 'PS') { ?>
                            <option selected value="PS">Pasaporte</option>
                        <?php } else { ?>
                            <option value="PS">Pasaporte</option>
                        <?php } ?>
                        <?php if ($this->datos[0]['usuTipoDocu'] == 'DNI') { ?>
                            <option selected value="DNI">Documento Nacional de Identificación</option>
                        <?php } else { ?>
                            <option value="DNI">Documento Nacional de Identificación</option>
                        <?php } ?>
                        <?php if ($this->datos[0]['usuTipoDocu'] == 'NIT') { ?>
                            <option selected value="NIT">Número de Identificación Tributaria</option>
                        <?php } else { ?>
                            <option value="NIT">Número de Identificación Tributaria</option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label>
                        Documento
                    </label>
                    <input name="txtDocumento" type="number" class="form-control" value="<?php echo $this->datos[0]['usuDocumento']; ?>">
                </div>
                <div class="form-group">
                    <label>
                        Nombres
                    </label>
                    <input type="text" name="txtNombre" class="form-control" value="<?php echo $this->datos[0]['usuNombre']; ?>">
                </div>
                <div class="form-group">
                    <label>
                        Apellidos
                    </label>
                    <input type="text" name="txtApellido" class="form-control" value="<?php echo $this->datos[0]['usuApellido']; ?>">
                </div>
                <div class="form-group">
                    <label>
                        Correo
                    </label>
                    <input type="text" class="form-control" name="txtCorreo" value="<?php echo $this->datos[0]['usuCorreo']; ?>">
                </div>
                <div class="form-group">
                    <label>
                        Telefono
                    </label>
                    <input type="number" class="form-control" name="txtTelefono" value="<?php echo $this->datos[0]['usuTelefono']; ?>">
                </div>
                <div class="form-group">
                    <input type="submit" id="enviarHuellas" class="btn btn-success" value="Guardar">&nbsp;<a href="<?php echo RUTA_URL . 'parametros/aprendices'; ?>" class="btn btn-danger">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="col-md-2"></div>
