<div class="col-md-3"></div>
<div class="col-md-6">
    <!-- general form elements -->
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $this->accion; ?></h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="post" action="<?php echo RUTA_URL . 'parametros/setprogramas'; ?>">
            <div class="box-body">
                <input type="hidden" name="txtCodigo" value="<?php echo $this->datos[0]['proId']; ?>">
                <div class="form-group">
                    <label for="exampleInputEmail1">Nombre</label>
                    <input name="txtNombre" type="text" value="<?php echo $this->datos[0]['proNombre']; ?>" class="form-control" id="exampleInputEmail1" placeholder="Programa">
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a href="<?php echo RUTA_URL . 'parametros/programas'; ?>" class="btn btn-danger">volver</a>
            </div>
        </form>
    </div>
</div>
<div class="col-md-3"></div>

