<!-- Content Header (Page header) -->
<script src="<?php echo COMMON; ?>js/datatable.js"></script>
<section class="content-header">
    <h1>
        Nuestro voluntariado
        <small>Administracion</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?php echo $this->metodo; ?></a></li>
        <li class="active"><?php echo $this->metodoaccion; ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid" id="vista">
        <div class="row">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Programas</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <button style="margin-bottom: 15px;" type="button" id="btnAgregarProgramas" class="btn btn-primary">Agregar</button>
                    <div class="table-responsive">
                        <table class="table table-bordered" id="example">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Programa</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php for ($i = 0; $i < count($this->programas); $i++): ?>
                                    <tr>
                                        <td><?php echo $i + 1; ?></td> 
                                        <td><?php echo ucwords(strtolower($this->programas[$i]['proNombre'])); ?></td>
                                        <td class="text-center">
                                            <button value="<?php echo $this->programas[$i]['proId']; ?>" class="btn btn-warning" id="btnEditarProgramas">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </button>
                                            <button data-id="<?php echo $this->programas[$i]['proId']; ?>" data-nom="<?php echo ucwords(strtolower($this->programas[$i]['proNombre'])); ?>" class="btn btn-danger" data-toggle="modal" data-target="#modalProgramas">
                                                <span class="glyphicon glyphicon-remove"></span>
                                            </button>
                                        </td>
                                    </tr>
                                <?php endfor; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" tabindex="-1" id="modalProgramas" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">Mensaje de confirmacion<button class="close" data-dismiss="modal">&times;</button></div>
                <div class="modal-body">
                    <h3>¿Esta seguro que desea eliminar esta actividad?</h3>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-warning" id="enviar">Si</a>
                    <a href="#" class="btn btn-danger" data-dismiss="modal">No</a>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    var RUTA_URL = 'http://localhost/vidar/';
    $(document).ready(function () {
        $('#modalProgramas').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var recipent = button.data('id')
            var nom = button.data('nom')
            var modal = $(this);
            modal.find('h3').text('¿Esta seguro que desea eliminar este programa: ' + nom + '?');
            modal.find('#enviar').attr('href', RUTA_URL + 'parametros/bajaprogramas/' + recipent);
        });
    });
</script>



