</div>
</div>
<!-- /.content-wrapper -->
<footer class="main-footer">
    <strong>Copyright &copy Smargeeks 2018
</footer>
</div>
<script src="<?php echo COMMON; ?>js/ajax.js"></script>
<script src="<?php echo $_layoutParams['ruta_js']; ?>script.js"></script>
<script src="<?php echo COMMON; ?>js/jquery-ui.min.js" type="text/javascript"></script>
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="<?php echo COMMON; ?>bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo COMMON; ?>raphael/raphael.min.js"></script>
<script src="<?php echo COMMON; ?>morris.js/morris.min.js"></script>
<script src="<?php echo COMMON; ?>jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<script src="<?php echo COMMON; ?>plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="<?php echo COMMON; ?>plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="<?php echo COMMON; ?>jquery-knob/dist/jquery.knob.min.js"></script>
<script src="<?php echo COMMON; ?>moment/min/moment.min.js"></script>
<script src="<?php echo COMMON; ?>bootstrap-daterangepicker/daterangepicker.js"></script>
<script src="<?php echo COMMON; ?>bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<script src="<?php echo COMMON; ?>plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script src="<?php echo COMMON; ?>jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script src="<?php echo COMMON; ?>fastclick/lib/fastclick.js"></script>
<script src="<?php echo COMMON; ?>dist/js/adminlte.min.js"></script>
<script src="<?php echo COMMON; ?>dist/js/demo.js"></script>
<script src="<?php echo COMMON; ?>plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script src="<?php echo COMMON; ?>bootstrapselect/dist/js/bootstrap-select.min.js" type="text/javascript"></script>
</body>
</html>